### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by SilverRainZ** [SilverRainZ/labots#1]
- [x] Replace decorator with `bot.say()` method, add more irc operations.
- More events:
  - [x] ACTION
  - [x] NOTICE
  - [ ] ISON
  - [x] LABOTS_MSG
- [x] Fix rejoin bug (Maybe caused by reconnection... )
- [x] Fix missing of QUIT/PART messages
- [x] Help command
