### ISSUE TITLE
LABots v2.0 Roadmap

### ISSUE THREAD

**Issue by SilverRainZ** [SilverRainZ/labots#12]
- [x] [pydle](https://github.com/Shizmob/pydle) integration
- [x] Architecture cleanup
- [x] Management API (HTTP based) server
    - [x] Load
    - [x] Unload
- [x] Management API client
    - [x] Load
    - [x] Unload
- [x] Deprecate auto reload
- [x] Upgrade old bots script https://github.com/SilverRainZ/bots/pull/1

Bots idea:

- Anti SPAM
- Anti flood
- Vote to kick?
- RTFM/Do not ask to ask

**Comment by SilverRainZ** [comment]
:tada: :tada: :tada:
